CREATE SCHEMA `swe642`;

COMMIT;

CREATE TABLE swe642.surveys
(
   ID   INT   NOT NULL PRIMARY KEY AUTO_INCREMENT,
   FIRST_NAME VARCHAR(30) NOT NULL,
   LAST_NAME  VARCHAR(30) NOT NULL,
   ADDRESS  VARCHAR(50) NOT NULL,
   CITY   VARCHAR(50) NOT NULL,
   STATE   VARCHAR(50) NOT NULL,
   ZIPCODE  VARCHAR(15) NOT NULL,
   TELEPHONE  VARCHAR(30) NOT NULL,
   EMAIL VARCHAR(50) NOT NULL,
   COMMENTS VARCHAR(200) NOT NULL,
   SURVEY_DATE VARCHAR(200) NOT NULL,
   INTEREST		ENUM('FRIENDS', 'TELEVISION', 'INTERNET', 'OTHER'),
   RECOMMENDATION	ENUM('LIKELY', 'VERY_LIKELY', 'UNLIKELY'),
   LIKES	SET("STUDENTS", "LOCATION", "CAMPUS", "ATMOSPHERE", "DORM_ROOMS", "SPORTS")
);

COMMIT;